### PR TITLE
Content

### PR DESCRIPTION
**Pull request by x37v**
* removed all audio content and put it into the private content repo
* added this as a submodule
  * you'll need to run `submodule init && submodule update` to get this after you merge
* created a makefile and companion script in *asteriskserver* to re-format/normalize all the audio that we can
* created a basic readme, *README-assets.md* indicating how to use it.

### CODE REVIEW

**Comment by x37v** [comment]
@kra If i didn't fuck anything up, and you run `make audio` then the file structure should be no different except the audio file extensions will now be '.sln' etc. instead of gsm.

but yes, before you build the derived assets, you won't have any audio in the installation.

**Comment by x37v** [comment]
On  0, Karl Anderson <notifications@github.com> wrote:
> kra commented on this pull request.
> 
> This looks like what we want, at least to start, but this a big diff that does two things
> - converts all the assets to the new store and install process
> - adds a requirement for gitlab private repo access
> 
> And it has two large effects that are worrying me
> - requires most of the acceptance test to be re-run this release
> - breaks the deploy process, which is "follow the steps in the top level README or README.virtualbox"
> 
> Can this be made smaller and deployable:
> - only the longmont and robotron sounds

oh huh, I had asked if you wanted all the audio content in the content repo and
you said yes.

Yeah, I could do some work to undo this and merge content from the private repo
and public.. it'll take me a bit to get to it. But then we won't get the benefit
of the normalized voice prompts.

> - README and README.virtualbox has instructions for getting and converting/installing the content 

your README.virtualbox already includes `populate assets directory` which I
assumed was the task I was doing, and is detailed in the README-assets.md I
provided.

> 
> The READMEs can be "have a populated src/assets directory either from the git
> submodule or manually copied" so long as a checkout can still be
> cloned/updated without gitlab access (yes, this is partly because I have not
> set up gitlab access yet, but also don't want to rely on it).

The gitlab submodule is only needed while we wait for your private github repo,
we could move the remote after that, and yeah, you can just copy the content
repo there but you still need to check it out and you'll have to ignore git
being annoying about it so I'm not sure it is worth not setting up your access.

**Comment by kra** [comment]
> On  0, Karl Anderson ***@***.***> wrote:
>  kra commented on this pull request.
> 
>  This looks like what we want, at least to start, but this a big diff that does two things
>  - converts all the assets to the new store and install process
>  - adds a requirement for gitlab private repo access
> 
>  And it has two large effects that are worrying me
>  - requires most of the acceptance test to be re-run this release
>  - breaks the deploy process, which is "follow the steps in the top level README or README.virtualbox"
> 
>  Can this be made smaller and deployable:
>  - only the longmont and robotron sounds
> oh huh, I had asked if you wanted all the audio content in the content repo and
> you said yes.

correct, this looks like what we want, at least to start, but this is a big diff. The goal is for all of the audio content to be in the content repo, but if we do it all at once it requires most of the acceptance test to be re-run this release, with only one ops person I want to avoid that risk if possible. I would like to make this work with the content which is currently coming from the content repo first.

> Yeah, I could do some work to undo this and merge content from the private repo
> and public.. it'll take me a bit to get to it. But then we won't get the benefit
> of the normalized voice prompts.

yes, we will want to add them in a later release.

>  - README and README.virtualbox has instructions for getting and converting/installing the content
> your README.virtualbox already includes `populate assets directory` which I
> assumed was the task I was doing, and is detailed in the README-assets.md I
> provided.

Referring to that would be a good description, if you don't want to do that, I'll do it.

**Comment by kra** [comment]
> @kra If i didn't fuck anything up, and you run make audio then the file structure should be no different except the audio file extensions will now be '.sln' etc. instead of gsm.

I didn't test it, but this looks to interact badly with the current ansible playbook that copies from the staging directory from the repo. If you don't have a working VM, I can test that.

**Comment by kra** [comment]
working parts of this have been merged in, thanks

**Pull request closed without merging**
