### PR TITLE
validate that user input is not empty before conversion to int

### PR DESCRIPTION
**Pull request by lboom**

### CODE REVIEW

**Comment by breedx2** [comment]
Progged had a similar issue.  Does this account for `#` and `*` too?

**Comment by breedx2** [comment]
For what it's worth, the way I tried to tackle this is in #343

**Comment by lboom** [comment]
oh! good catch. I did not test for that.

**Comment by lboom** [comment]
Updated. I am handling exclusively [ '', '#', '*' ] in this case. Testing works.

**Comment by breedx2** [comment]
Better hope those hackers don't enter an `A` or a `B`...

**Comment by lboom** [comment]
If they do, thats their problem. Ship it.

**Pull request merged**
